
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: docker-image-v0.5.4

on:
 workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    - run: rm .env.dev
    - run: npm run build --if-present
    - run: ls -lrt
    
    - name: Clone Vue codebase
      run: git clone https://github.com/ThingsPanel/visual-editor.git

    - run: cd visual-editor
    - run: npm install -g pnpm
    
    - name: Build V
      run: |
       pnpm install --frozen-lockfile
       pnpm run build
      working-directory: ./visual-editor
        
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
      
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: thingspanel/thingspanel-vue:v0.5.4
